@Api_HostAddress = http://localhost:5101

GET {{Api_HostAddress}}/customers
Accept: application/json

###
POST {{Api_HostAddress}}/customers
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@tesla.com",
  "gitHubUserName": "gurame",
  "dateOfBirth": "1980-01-01"
}

###
GET {{Api_HostAddress}}/customers/f13c7cfe-459d-46c2-a2db-c985f0fb5d5f
Accept: application/json

###
PUT {{Api_HostAddress}}/customers/f13c7cfe-459d-46c2-a2db-c985f0fb5d5f

Content-Type: application/json

{
  "name": "John Doe Jr.",
  "email": "johndoe@netflix.com",
  "gitHubUserName": "johndoejr",
  "dateOfBirth": "1980-01-01"
}

###
DELETE {{Api_HostAddress}}/customers/b7ba77bf-3bc9-4a40-bc6c-46b81945aeed